config/routes.rb
CoffeeSite::Application.routes.draw do

  devise_for :users

  namespace :admin do
    resources :coffee_types
    resources :images
    resources :categories
    resources :places
  end

  resources :admin, :only => :index

  match "home" => "pages#home"

  match "price" => "pages#price"

  match "images" => "pages#images"

  match "video" => "pages#video"

  namespace :my do
    resources :places, :controller => 'places'
  end

  match "places" => "places#index"
  match "places/get" => "places#get_places"

  
  root :to => 'pages#home'

end

app/models/category.rb
# -*- encoding : utf-8 -*-
class Category < ActiveRecord::Base

	mount_uploader :image, ImageUploader
	
	has_many :places, :dependent => :destroy

  def as_json(args = {})
    super(args)
  end

  def sort_places
    places.where("enable = ?", true)
  end

end

app/models/coffee_type.rb
# -*- encoding : utf-8 -*-
class CoffeeType < ActiveRecord::Base
end

app/models/painting.rb
# -*- encoding : utf-8 -*-
class Painting < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/place.rb
# -*- encoding : utf-8 -*-
class Place < ActiveRecord::Base

	belongs_to :category
	belongs_to :user

	attr_protected :enable


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable, :confirmable and :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :places, :dependent => :destroy
end

app/controllers/admin/categories_controller.rb
# -*- encoding : utf-8 -*-
class Admin::CategoriesController < AdminController

  def index
  	@categories = Category.all
  end

  def new
  	@category = Category.new

  	respond_to do |format|
  		format.html
  		format.json {render :json}
  	end
  end

  def create
  	@category = Category.new(params[:category])
  	@category.save
  	redirect_to admin_categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])
    redirect_to admin_categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end
end

app/controllers/admin/coffee_types_controller.rb
# -*- encoding : utf-8 -*-
class Admin::CoffeeTypesController < AdminController

	def index
		@coffee_types = CoffeeType.all
	end

	def new
		@coffeetype = CoffeeType.new

		respond_to do |format|
			format.html
			format.json { render json: @coffeetype }
		end
	end

	def create
		@coffeetype = CoffeeType.new(params[:coffee_type])
		@coffeetype.save
		redirect_to admin_coffee_types_path
	end

	def destroy
		@coffee_article = CoffeeType.find(params[:id])
		@coffee_article.destroy
		redirect_to admin_coffee_types_path
	end

end

app/controllers/admin/images_controller.rb
# -*- encoding : utf-8 -*-
class Admin::ImagesController < AdminController

  def index
  	@paintings = Painting.all
  end

  def new
	  	@painting = Painting.new

	  	respond_to do |format|
	  		format.html
	  		format.json { render json: @painting }
	  	end
  end

  def create
  		@painting = Painting.new(params[:painting])
  		@painting.save
  		redirect_to admin_images_path
  end

  def destroy
    @painting = Painting.find(params[:id])
    respond_to do |format|
      if @painting.destroy
        format.json {render :json =>{:status => 'ok'}}
      else
        format.json{render :json, :status => :unprocessable_entity}
      end
    end
  end

end

app/controllers/admin/places_controller.rb
# -*- encoding : utf-8 -*-
class Admin::PlacesController < AdminController

  def index
    if params[:filter] == "untested_places"
  	  @places = Place.where('enable = ?', false)
    else
      get_category
      @places = @category.places.where('enable = ?', true)
    end

    respond_to do |format|

      format.html
      format.json {render :json => @places}
    end
  end

  def show
  end

  def new
    get_category
  	@place = Place.new
  	respond_to do |format|
  		format.html
  		format.json {render :json => @place}
  	end
  end

  def create
    @category = Category.find(params[:place][:category_id])
  	@place = @category.places.new(params[:place].merge(:enable => true), :without_protection => true)
    @place.save
  	redirect_to admin_places_path(:category_id => @category.id)
  end

  def edit 
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @place }
    end
  end

  def update
    @place = Place.find(params[:id])
    @place.update_attributes(params[:place], :without_protection => true)
    if params[:back_url] == 'untested_places'
      redirect_to admin_places_path(:filter => 'untested_places')
    else
      redirect_to admin_places_path(:category_id => @place.category_id)
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    if params[:back_url] == 'untested_places'
      redirect_to admin_places_path(:filter => 'untested_places')
    else
      redirect_to admin_places_path(:category_id => @place.category_id)
    end
  end

  private

  def get_category
    @category = Category.find(params[:category_id])
  end
end

app/controllers/admin_controller.rb
# -*- encoding : utf-8 -*-
class AdminController < ApplicationController

  layout 'admin'

  def index
  end
  
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/my/places_controller.rb
# -*- encoding : utf-8 -*-
class My::PlacesController < ApplicationController

  before_filter :authenticate_user!

  def index
  	@categories = Category.all
  end

  def new
  	@place = Place.new

  	respond_to do |format|
  		format.html
  		format.json { render :json }
  	end
  end

  def create
  	@place = current_user.places.new(params[:place])
  	@place.save
  	redirect_to places_path
  end

  def get_places
  	@categories = Category.all

  	render :json => @categories, :include => :places
  end
  
end

app/controllers/pages_controller.rb
# -*- encoding : utf-8 -*-
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def price
    @title = "Coffee Price"
    @coffee_articles = CoffeeType.all
  end

  def images
    @title = "Images"
  end

  def video
    @title = "Video"
  end

  def gmaps
    @title = "Google maps"
  end
  
end

app/controllers/places_controller.rb
# -*- encoding : utf-8 -*-
class PlacesController < ApplicationController

  def index
  	@categories = Category.all
  end

  def get_places
  	@categories = Category.all

  	render :json => @categories.as_json(:methods => :sort_places)
  end
  
end

app/helpers/admin/categorys_helper.rb
module Admin::CategorysHelper
end

app/helpers/admin/gmaps_helper.rb
# -*- encoding : utf-8 -*-
module Admin::GmapsHelper
end

app/helpers/admin/images_helper.rb
# -*- encoding : utf-8 -*-
module Admin::ImagesHelper
end

app/helpers/admin/posts_helper.rb
# -*- encoding : utf-8 -*-
module Admin::PostsHelper
end

app/helpers/admin_helper.rb
# -*- encoding : utf-8 -*-
module AdminHelper
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper


	def title
		base_title = "Coffee Site"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end

	def navigation_panel
	    paths = {
	      "Home" => "/home",
	      "Coffee Price" => "/price",
	      "Images" => "/images",
	      "Video" => "/video",
	      "Google Maps" => "/places",
        }

        a = "<div id='dl_link'>"
        paths.each {|key, value|
	      if request.path.include?(value) 
	        a += content_tag(:a, key, :href => value, :class => "first")
	      elsif request.path == "/" && value == "/home"
	      	a += content_tag(:a, key, :href => value, :class => "first")  
	      else
	      	a += content_tag(:a, key, :href => value, :class => "butt")
	  	  end
	    }
	    a += "</div>"
	    a.html_safe  
	end
end

app/helpers/my_places_helper.rb
module MyPlacesHelper
end

app/helpers/pages_helper.rb
# -*- encoding : utf-8 -*-
module PagesHelper
end

app/helpers/places_helper.rb
# -*- encoding : utf-8 -*-
module PlacesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category], :multipart => true do |f| %>

  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div>
  	<%= f.file_field :image %>
  	<%= image_tag @category.image if @category.image? %>
  </div>
  <div>
    <%= f.submit "Сохранить" %>
  </div>

<% end %>

app/views/admin/categories/edit.html.erb
<h2>Редактирование категории</h2>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<% @categories.each do |c| %>
	<div class="category_admin">
		<%= link_to c.name, admin_places_path(:category_id => c.id) %>
		<%= link_to image_tag("admin/close-icon.gif"), admin_category_path(c), :method => :delete %>
		<%= link_to image_tag("admin/edit_icon.jpg"), edit_admin_category_path(c) %>
	</div>
<% end %>

<div><%= link_to "Новая категория", new_admin_category_path, :id => "new_category" %></div>

app/views/admin/categories/new.html.erb
<h1>Новая категория</h1>

<%= render "form" %>

app/views/admin/places/_form.html.erb
<%= form_for [:admin, @place] do |f| %>
	<div>
		<%= f.label "Широта" %>
		<%= f.text_field :lat, :id => 'lat' %>
	</div>
	<div>	
		<%= f.label "Долгота" %>
		<%= f.text_field :long, :id => 'lag' %>
	</div>
	<div>
		<%= f.label 'Выберите категорию' %>
		<%= f.select :category_id, Category.all.collect {|c|[ c.name, c.id ]} %>
	</div>
	<div>
		<%= f.label 'Утверждена' %>
		<%= f.check_box :enable %>
	</div>
		<%= text_field_tag(:back_url, params[:back_url], :class => 'disabled') %>
		<%= f.submit "Сохранить координаты" %>
<% end %>

app/views/admin/places/edit.html.erb
<% content_for :head do %>
    <%= javascript_include_tag 'https://maps.google.com/maps/api/js?sensor=true&language=ru' %>
    <%= javascript_include_tag 'admin/places' %>
<% end %>

<h2>Редактирование метки</h2>

<%= render 'form' %>

app/views/admin/places/index.html.erb
<%= content_tag(:div, flash.notice) %>
<%if params[:filter] != 'untested_places' %>
	<h2><%= @category.name %></h2>
	<%= link_to "Добавить координаты", new_admin_place_path(:category_id => params[:category_id]) %>
<% else %>
	<h2>Непроверенные метки</h2>
<% end %>
<% @places.each do |c| %>
	<div>
		<%= c.lat %>,
		<%= c.long %>
		<% if params[:filter] == 'untested_places' %>
			<%= link_to image_tag('admin/edit_icon.jpg'), edit_admin_place_path(c, :back_url => 'untested_places') %>
			<%= link_to image_tag("admin/close-icon.gif"), admin_place_path(c, :back_url => 'untested_places'), :method => :delete %>
		<% else %>
			<%= link_to image_tag('admin/edit_icon.jpg'), edit_admin_place_path(c) %>
			<%= link_to image_tag("admin/close-icon.gif"), admin_place_path(c), :method => :delete %>
		<% end %>
	</div>
<% end %>

app/views/admin/places/new.html.erb
<% content_for :head do %>
    <%= javascript_include_tag 'https://maps.google.com/maps/api/js?sensor=true&language=ru' %>
    <%= javascript_include_tag 'admin' %>
<% end %>

<h1>Добавление координат</h1>

<%= render "form" %>

<%= link_to "Посмотреть и отметить на карте", '#', :id => "link_to_maps" %>

<%= content_for :head do %>
	<script type="text/javascript">
		window.category_id = <%= @category.id %>
	</script>
<% end %>

app/views/my/places/_form.html.erb
<%= form_for @place, :url => :my_places do |p| %>
	<div>
		<%= p.label 'Широта' %>
		<%= p.text_field :lat, :id => "lat" %>
	</div>
	<div>
		<%= p.label 'Долгота' %>
		<%= p.text_field :long, :id => 'lag' %>
	</div>
	<div>
		<%= p.label 'Выберите категорию' %>
		<%= p.select :category_id, Category.all.collect {|c|[ c.name, c.id ]}, {:include_blank => true} %>
	</div>
	<div>
		<%= p.submit 'Сохранить метку' %>
	</div>
<% end %>

app/views/my/places/index.html.erb
<% content_for :head do %>
    <%= javascript_include_tag 'https://maps.google.com/maps/api/js?sensor=true&language=ru' %>
    <%= javascript_include_tag 'places' %>
<% end %>

<div id="cell">
            
    <div id="content_left" style="width: 507px;">
            	
        <div id="content_left_opacity" class="width2"></div>
                
            <div style="margin-left:21px; margin-top: 23px; padding-right: 20px; position:relative;">
                
                <div style="width: 450px; height: 400px;" id="map_canvas"></div>
                     
            </div>
                
    </div>
            
    <div id="content_right" style="width: 173px;">
                
        <div>Категории</div>        
        <% @categories.each do |c| %>
            <div>
                <input type="checkbox" id=<%= c.id %> />
                <%= c.name %>
            </div>
        <% end %>
            	
    </div>
            
</div>

app/views/my/places/new.html.erb
<% content_for :head do %>
    <%= javascript_include_tag 'https://maps.google.com/maps/api/js?sensor=true&language=ru' %>
    <%= javascript_include_tag 'my_places' %>
<% end %>

<h3>Добавьте свою метку</h3>

<%= render 'form' %>

<%= link_to 'Добавить метку на карте', '#', :id => 'link_to_maps' %>

app/views/places/index.html.erb
<% content_for :head do %>
    <%= javascript_include_tag 'https://maps.google.com/maps/api/js?sensor=true&language=ru' %>
    <%= javascript_include_tag 'places' %>
<% end %>

<div id="cell">
            
    <div id="content_left" style="width: 507px;">
            	
        <div id="content_left_opacity" class="width2"></div>
                
            <div style="margin-left:21px; margin-top: 23px; padding-right: 20px; position:relative;">
                
                <div style="width: 450px; height: 400px;" id="map_canvas"></div>
                     
            </div>
                
    </div>
            
    <div id="content_right" style="width: 173px;">
                
        <div>Категории</div>        
        <% @categories.each do |c| %>
            <div>
                <input type="checkbox" id=<%= c.id %> />
                <%= c.name %>
            </div>
        <% end %>

        <%= link_to 'Добавить свою метку', new_my_place_path %>
            	
    </div>
            
</div>