config/routes.rb
CoffeeSite::Application.routes.draw do

  devise_for :users

  namespace :admin do
    resources :coffee_types
    resources :images
    resources :categories
    resources :places
  end

  resources :admin, :only => :index

  match "home" => "pages#home"

  match "price" => "pages#price"

  match "images" => "pages#images"

  match "video" => "pages#video"

  namespace :my do
    resources :places, :controller => 'places'
  end

  match "places" => "places#index"
  match "places/get" => "places#get_places"

  
  root :to => 'pages#home'

end

app/models/category.rb
# -*- encoding : utf-8 -*-
class Category < ActiveRecord::Base

	mount_uploader :image, ImageUploader
	
	has_many :places, :dependent => :destroy

  def as_json(args = {})
    super(args)
  end

  def sort_places
    places.where("enable = ?", true)
  end

end

app/models/coffee_type.rb
# -*- encoding : utf-8 -*-
class CoffeeType < ActiveRecord::Base
end

app/models/painting.rb
# -*- encoding : utf-8 -*-
class Painting < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/place.rb
# -*- encoding : utf-8 -*-
class Place < ActiveRecord::Base

	belongs_to :category
	belongs_to :user

	attr_protected :enable


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable, :confirmable and :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :places, :dependent => :destroy
end

app/controllers/admin/images_controller.rb
# -*- encoding : utf-8 -*-
class Admin::ImagesController < AdminController

  def index
  	@paintings = Painting.all
  end

  def new
	  	@painting = Painting.new

	  	respond_to do |format|
	  		format.html
	  		format.json { render json: @painting }
	  	end
  end

  def create
  		@painting = Painting.new(params[:painting])
  		@painting.save
  		redirect_to admin_images_path
  end

  def destroy
    @painting = Painting.find(params[:id])
    respond_to do |format|
      if @painting.destroy
        format.json {render :json =>{:status => 'ok'}}
      else
        format.json{render :json, :status => :unprocessable_entity}
      end
    end
  end

end

app/controllers/admin_controller.rb
# -*- encoding : utf-8 -*-
class AdminController < ApplicationController

  layout 'admin'

  def index
  end
  
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/my/places_controller.rb
# -*- encoding : utf-8 -*-
class My::PlacesController < ApplicationController

  before_filter :authenticate_user!

  def index
  	@categories = Category.all
  end

  def new
  	@place = Place.new

  	respond_to do |format|
  		format.html
  		format.json { render :json }
  	end
  end

  def create
  	@place = current_user.places.new(params[:place])
  	@place.save
  	redirect_to places_path
  end

  def get_places
  	@categories = Category.all

  	render :json => @categories, :include => :places
  end
  
end

app/controllers/pages_controller.rb
# -*- encoding : utf-8 -*-
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def price
    @title = "Coffee Price"
    @coffee_articles = CoffeeType.all
  end

  def images
    @title = "Images"
  end

  def video
    @title = "Video"
  end

  def gmaps
    @title = "Google maps"
  end
  
end

app/controllers/places_controller.rb
# -*- encoding : utf-8 -*-
class PlacesController < ApplicationController

  def index
  	@categories = Category.all
  end

  def get_places
  	@categories = Category.all

  	render :json => @categories.as_json(:methods => :sort_places)
  end
  
end

app/helpers/admin/categorys_helper.rb
module Admin::CategorysHelper
end

app/helpers/admin/gmaps_helper.rb
# -*- encoding : utf-8 -*-
module Admin::GmapsHelper
end

app/helpers/admin/images_helper.rb
# -*- encoding : utf-8 -*-
module Admin::ImagesHelper
end

app/helpers/admin/posts_helper.rb
# -*- encoding : utf-8 -*-
module Admin::PostsHelper
end

app/helpers/admin_helper.rb
# -*- encoding : utf-8 -*-
module AdminHelper
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper


	def title
		base_title = "Coffee Site"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end

	def navigation_panel
	    paths = {
	      "Home" => "/home",
	      "Coffee Price" => "/price",
	      "Images" => "/images",
	      "Video" => "/video",
	      "Google Maps" => "/places",
        }

        a = "<div id='dl_link'>"
        paths.each {|key, value|
	      if request.path.include?(value) 
	        a += content_tag(:a, key, :href => value, :class => "first")
	      elsif request.path == "/" && value == "/home"
	      	a += content_tag(:a, key, :href => value, :class => "first")  
	      else
	      	a += content_tag(:a, key, :href => value, :class => "butt")
	  	  end
	    }
	    a += "</div>"
	    a.html_safe  
	end
end

app/helpers/my_places_helper.rb
module MyPlacesHelper
end

app/helpers/pages_helper.rb
# -*- encoding : utf-8 -*-
module PagesHelper
end

app/helpers/places_helper.rb
# -*- encoding : utf-8 -*-
module PlacesHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/layouts/_footer.html.erb
<div style="float:left; margin-top: 15px;"><h5 class="white">© 2011 Coffee Break</h5></div>
<div style="float:right; margin-top: 15px;"><h5 style="color:#FFF;">Template by <a href="#" class="blue">One Dollar Templates</a></h5></div>

app/views/layouts/_navigation.html.erb
<%= navigation_panel %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "admin", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "lightbox" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>

<body>
  
  <div class="nav_menu">

    <%= link_to "Типы кофе", admin_coffee_types_path %>
    <%= link_to "Изображеньки", admin_images_path %>
    <%= link_to "Категории меток", admin_categories_path %>
    <%= link_to "Непроверенные", admin_places_path(:filter => "untested_places") %>

  </div>

  <div id="admin_content"><%= yield %></div>            
          
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "lightbox" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="container">
      
      <div id="login">
        <% if user_signed_in? %>
          Вы зашли как <%= current_user.name %>. Неправильно?
          <%= link_to "Выход", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Регистрация", new_user_registration_path %> или <%= link_to "Вход", new_user_session_path %>
        <% end %>
      </div>

    	<div id="header">
        <h1>Coffee<span style="color:#FFF">Break</span></h1>
      </div>
      
      <div id="body">
      
      	<div id="container_link"><%= render "layouts/navigation" %></div>
          
          <div id="content">
          	
          	<%= yield %>
              
          </div>
          
          <div id="footer"><%= render "layouts/footer"%></div>
          
      </div>
      
  </div>
</body>
</html>

app/views/pages/gmaps.html.erb
			<div id="cell">
            
    			<div id="content_left" style="width: 507px;">
            	
            		<div id="content_left_opacity" class="width2"></div>
                
              	    <div style="margin-left:21px; margin-top: 23px; padding-right: 20px; position:relative;">
                    <div style="width:100%; height: 500px;" id="map_canvas"></div>
                     
                    </div>
                
        		</div>
            
            	<div id="content_right" style="width: 173px;">
                
                	 <h2 style="font-size:21px;">About</h2>
                     <hr color="#cccccc" size="0.5" width="160px" style="margin-left: 0px; margin-top: 7px;">
                     
                     <h5 style="margin-top: 16px; margin-right: 10px;">Маркер человечка - ваше местоположение. Если нажать на маркер автомата с кофе, будет показан его адрес.</h5> <br>
                     
                     <h2 style="font-size:21px;">Links</h2>
                     <hr color="#cccccc" size="0.5" width="160px" style="margin-left: 0px; margin-top: 7px;">
                     
                    <dl>
                    	<dt><a href="http://maps.google.ru/" class="blue"><h5>Google maps</h5></a></dt>
                    </dl>    
            	
           		</div>
            
            </div>

app/views/pages/home.html.erb
<%= content_tag(:div, flash.notice) %>
<div id="cell">
            
    <div id="content_left">
	            	
	    <div id="content_left_opacity">&nbsp;</div>
	    <div><img src="assets/front/animation/1.jpg" id="image"></div>
                
    </div>
            
    <div id="content_right">
        <h2>Welcome</h2>
        <hr>
                
        <span id="put_cookie"><h5>Добро пожаловать на сайт, посвященный кофе, здесь вы можете:</h5></span>
                
        <ul type="circle">
            <li><h5>Сделать расчеты покупки кофе в нашем магазине</h5></li>
            <li><h5>Посмотреть красивые фоточки чашечек с кофе</h5></li> 
            <li><h5>Взглянуть на видео о кофе</h5></li> 
            <li><h5>Узнать где близжайший к вам кофейный автоматик</h5></li> 
        </ul>
                
        <h5>Наслаждайтесь путешествием в кофейную страну!</h5>
    </div>
            
</div>
       

app/views/pages/images.html.erb
<div id="cell">
            
    			<div id="content_left" style="width: 507px;">
            	
            		<div id="content_left_opacity" class="width2"></div>
                
              	    <div style="margin-left:21px; margin-top: 23px; padding-right: 20px; position:relative;">
                    
                    <h2>Images</h2>
                
               	    <hr color="#cccccc" size="0.5" width="460px">
                    
        		</div>
            
            	<div id="content_right" style="width: 180px;">
                
                	 <h2 style="font-size:21px;">About</h2>
                     <hr color="#cccccc" size="0.5" width="160px" style="margin-left: 0px; margin-top: 7px;">
                     
                     <h5 style="margin-top: 16px; margin-right: 10px;">Сижу грущу, пустая кружка.<br>О боги! Ну зачем вы так. Мне не нужна теперь подушка.<br> Мне бы на кофе четвертак!</h5> <br>
                     
                     <h2 style="font-size:21px;">Links</h2>
                     <hr color="#cccccc" size="0.5" width="160px" style="margin-left: 0px; margin-top: 7px;">
                     
                    <dl>
                    	<dt><a href="http://www.huddletogether.com/projects/lightbox2/" class="blue"><h5>LightBox</h5></a></dt> 
                    </dl>    
            	
           		</div>
            
            </div>

app/views/pages/price.html.erb
<div id="cell">
            
    			<div id="content_left" style="width: 507px;">
            	
            		<div id="content_left_opacity" class="width2"></div>
                
              	    <div style="margin-left:21px; margin-top: 20px; padding-right: 20px; position:relative; ">
                    
                   		 <h2>About coffee</h2>
                	
               	   		 <hr color="#cccccc" size="0.5" width="460px">
                         
                         <% @coffee_articles.each do |coffee| %>
                            <div class="coffee_article">
                              <div class="coffee_name"><%= coffee.name %></div>
                              <div class="coffee_price"><%= coffee.price %></div>
                            </div>
                         <% end %>
                   	
                   
                   </div>
                 
        		</div>
            
            	<div id="content_right" style="width: 173px; min-height: 230px;">
                
                 
                     <h2 style="font-size:21px;">About</h2>
                     <hr color="#cccccc" size="0.5" width="160px" style="margin-left: 0px; margin-top: 7px;">
                     
                     <h5 style="margin-top: 16px; margin-right: 10px;">Можете расчитать стоимость заказа. Выберите тип напитка и колличество чашек. Будет рассчитана сумма и итого.</h5> <br>
                     
                     <h2 style="font-size:21px;">Discount</h2>
                     <hr color="#cccccc" size="0.5" width="160px" style="margin-left: 0px; margin-top: 7px;">
                     <h5 style="margin-top: 16px; margin-right: 10px;">При расчёте суммы и итого наименьшая сумма по одному из типов напитка будет обнулена. </h5>
                    
           		</div>
            
            </div>

app/views/pages/video.html.erb
			<div id="cell">
    			<div id="content_left" style="width: 507px;">
            	
            		<div id="content_left_opacity" class="width2"></div>
                
              	    <div style="margin-left:21px; margin-top: 23px; padding-right: 20px; position:relative; ">
                    
                   		 <h2>Video</h2>
                	
               	   		 <hr color="#cccccc" size="0.5" width="460px">
						
                      <div id='mediaplayer'></div>
                      
                    </div> 
        		</div>
            
            	<div id="content_right" style="width: 173px;">
                
                     <h2 style="font-size:21px;">About</h2>
                     <hr color="#cccccc" size="0.5" width="160px" style="margin-left: 0px; margin-top: 7px;">
                     
                     <h5 style="margin-top: 16px; margin-right: 10px;">Тихо упала ночь.<br> Сахар утонул на дне.<br> Сливки выплыли.</h5> <br>
                    
                     <h2 style="font-size:21px;">Links</h2>
                     <hr color="#cccccc" size="0.5" width="160px" style="margin-left: 0px; margin-top: 7px;">
                     
                     <dl>
                    	<dt><a href="http://www.longtailvideo.com/" class="blue"><h5>JW Player</h5></a></dt> 
                    </dl>    
           		</div>
            
            </div>